Repository Talend/design-system, pull requests merged in 2021-04, with the labels that each got.

#103 doc(Storybook): Design Tokens resolution
  .storybook/main.js
  .storybook/preview-head.html
  package.json
  src/components/Link/docs/Link.stories.mdx
Labels: enhancement

#106 fix(ThemeProvider): Source Sans Pro instead of Open Sans
  src/components/ThemeProvider/index.js
Labels: bug

#104 doc(Storybook): Docs tab by default
  .storybook/main.js
  package.json
Labels: enhancement

#65 feat(components): stepper
  .changeset/angry-apples-breathe.md
  src/components/Stepper/Step/Step.style.ts
  src/components/Stepper/Step/Step.tsx
  src/components/Stepper/Step/index.ts
  src/components/Stepper/Step/variations/Step.disabled.tsx
  src/components/Stepper/Step/variations/Step.enabled.tsx
  src/components/Stepper/Step/variations/Step.error.tsx
  src/components/Stepper/Step/variations/Step.progress.tsx
  src/components/Stepper/Step/variations/Step.skeleton.tsx
  src/components/Stepper/Step/variations/Step.validated.tsx
  src/components/Stepper/Stepper.style.ts
  src/components/Stepper/Stepper.tsx
  src/components/Stepper/docs/Stepper.overview.stories.mdx
  src/components/Stepper/docs/Stepper.step.stories.mdx
  src/components/Stepper/index.ts
  src/index.js
Labels: good first issue

#119 fix(CI/release): remove prepublishOnly which makes changeset fails
  .github/workflows/publish.yml
  package.json
Labels: need review

#118 doc(Storybook): Themes
  .storybook/preview-head.html
  src/docs/Themes.component.js
  src/docs/index.js
  src/themes/dark.theme.ts
  src/themes/docs/Dark.stories.mdx
  src/themes/docs/Light.stories.mdx
  src/themes/docs/Themes.stories.mdx
  src/tokens/colors.tokens.ts
  src/tokens/radii.tokens.js
Labels: enhancement

#123 doc(Storybook): Figma embed
  .storybook/preview.js
  src/components/Button/docs/Button.stories.mdx
  src/components/Form/docs/Input.checkbox.stories.mdx
  src/components/Form/docs/Input.password.stories.mdx
  src/components/Form/docs/Input.radio.stories.mdx
  src/components/Form/docs/Input.range.stories.mdx
  src/components/Form/docs/Input.search.stories.mdx
  src/components/Form/docs/Input.select.stories.mdx
  src/components/Form/docs/Input.stories.mdx
  src/components/Form/docs/Input.switch.stories.mdx
  src/components/Form/docs/Input.textarea.stories.mdx
  src/components/Tabs/docs/Tabs.stories.mdx
  src/components/Tag/docs/Tag.stories.mdx
  src/components/Toggle/docs/Toggle.stories.mdx
  src/components/Tooltip/docs/Tooltip.stories.mdx
  src/docs/FigmaIframe.component.js
  src/docs/index.js
Labels: enhancement, need review

#122 doc(components/Button): guidelines
  src/components/Button/docs/Button.stories.mdx
Labels: enhancement, need review

#117 feat(Stepper): horizontal
  src/components/Stepper/Progress/Progress.style.ts
  src/components/Stepper/Progress/Progress.tsx
  src/components/Stepper/Progress/index.ts
  src/components/Stepper/Progress/variations/Progress.horizontal.ts
  src/components/Stepper/Progress/variations/Progress.vertical.ts
  src/components/Stepper/Step/Step.tsx
  src/components/Stepper/Step/variations/Step.progress.tsx
  src/components/Stepper/Step/variations/Step.skeleton.tsx
  src/components/Stepper/Stepper.style.ts
  src/components/Stepper/Stepper.tsx
  src/components/Stepper/docs/Stepper.overview.stories.mdx
  src/components/Stepper/index.ts
  src/components/Stepper/variations/Stepper.horizontal.ts
  src/components/Stepper/variations/Stepper.vertical.ts
Labels: enhancement, need review

#128 chore(PR_TEMPLATE): add changelog in PR checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: good first issue, need review

#125 fix(IconsProvider): prevent multiple rendering
  .changeset/stale-rice-happen.md
  src/components/IconsProvider/IconsProvider.test.tsx
  src/components/IconsProvider/IconsProvider.tsx
  src/components/IconsProvider/__snapshots__/IconsProvider.test.tsx.snap
  src/docs/Icons.component.js
  yarn.lock
Labels: bug, need review
