Repository Talend/design-system, pull requests merged in 2021-09, with the labels that each got.

#208 doc(Accordion): Clarification and application of the doc
  .changeset/silver-weeks-chew.md
  src/components/Accordion/Accordion.style.ts
  src/components/Accordion/docs/Accordion.stories.mdx
Labels: documentation

#211 chore(Next): Remove Next
  .gitignore
  .npmignore
  next-env.d.ts
  next.config.js
  package.json
  pages/App.css
  pages/_app.tsx
  pages/index.tsx
  yarn.lock
Labels: enhancement, need review, dependencies

#216 fix(components/InlineMessage): className was missing for variations
  .changeset/happy-bottles-build.md
  src/components/InlineMessage/InlineMessage.stories.tsx
  src/components/InlineMessage/InlineMessage.style.ts
  src/components/InlineMessage/InlineMessage.tsx
  src/components/InlineMessage/docs/InlineMessage.stories.mdx
  src/components/InlineMessage/variations/InlineMessage.destructive.tsx
  src/components/InlineMessage/variations/InlineMessage.information.tsx
  src/components/InlineMessage/variations/InlineMessage.success.tsx
  src/components/InlineMessage/variations/InlineMessage.warning.tsx
Labels: enhancement, need review

#224 fix(components/InlineMessage): text-align at start
  .changeset/kind-rats-taste.md
  src/components/InlineMessage/InlineMessage.style.ts
Labels: enhancement, need review

#247 chore(dependencies): upgrade
  package.json
  src/components/Icon/__snapshots__/Icon.test.js.snap
  yarn.lock
Labels: enhancement, dependencies

#248 chore(dependencies): resolutions
  package.json
  yarn.lock
Labels: enhancement, dependencies
