Repository Talend/design-system, pull requests merged in 2021-05, with the labels that each got.

#135 fix(components): Inline Message
  src/components/InlineMessage/InlineMessage.style.ts
  src/components/InlineMessage/InlineMessage.tsx
  src/components/InlineMessage/docs/InlineMessage.stories.mdx
  src/components/InlineMessage/variations/InlineMessage.destructive.tsx
Labels: need review, need visual approval

#138 doc(Forms): Radio and Checkbox pages
  .storybook/preview-head.html
  src/Status.stories.mdx
  src/components/Form/Field/Input/Input.Checkbox.tsx
  src/components/Form/Field/Input/Input.Radio.tsx
  src/components/Form/Field/Input/styles/Input.Inline.style.ts
  src/components/Form/docs/Input.checkbox.stories.mdx
  src/components/Form/docs/Input.radio.stories.mdx
  src/styled.d.ts
  src/themes/dark.theme.ts
  src/themes/light.theme.ts
Labels: enhancement, need review

#143 doc(Storybook): WithSelector component
  src/components/Link/docs/Link.stories.mdx
  src/docs/WithSelector.component.js
  src/docs/index.js
Labels: documentation, enhancement, need review

#49 fix(IconsProvider): do not load twice
  src/components/IconsProvider/IconsProvider.tsx
Labels: need review

#37 test(Icon): add
  src/components/Icon/Icon.test.js
  src/components/Icon/__snapshots__/Icon.test.js.snap
  test-utils.js
Labels: need review

#153 fix(Link): underline
  .changeset/new-icons-listen.md
  src/components/Link/Link.spec.tsx
  src/components/Link/Link.style.ts
  src/components/Link/Link.tsx
  src/components/Link/docs/Link.stories.mdx
Labels: enhancement, need review
